{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-consumer
  labels:
    app: sentinel-consumer
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: sentinel-consumer
  template:
    metadata:
      labels:
        app: sentinel-consumer
    spec:
      {{- with .Values.consumer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.consumer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z postgres 5432; do echo "Waiting for Postgres..."; sleep 2; done;']
        - name: wait-for-redpanda
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z redpanda 9092; do echo "Waiting for Redpanda..."; sleep 2; done;']

      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumer.image.pullPolicy }}
          command: ["python", "-m", "src.inference.consumer"]

          envFrom:
            - secretRef:
                name: postgres-secret

          env:
            {{- if .Values.consumer.env }}
            {{- toYaml .Values.consumer.env | nindent 12 }}
            {{- end }}

          resources:
            {{- toYaml .Values.consumer.resources | nindent 12 }}
{{- end }}
