apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  labels:
    app.kubernetes.io/name: sentinel-config
    app.kubernetes.io/environment: {{ .Values.global.environment }}

data:
  KAFKA_BROKER_URL: "redpanda-service:{{ .Values.redpanda.service.port }}"
  REDIS_URL: "redis://redis-service:{{ .Values.redis.service.port }}"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "{{ .Values.redis.service.port }}"
