repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: '^infrastructure/helm/.*'
      - id: check-toml
      - id: debug-statements
      - id: check-added-large-files
        args: ['--maxkb=5120']

  # Conventional Commits Linter
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # YAML Linter
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        exclude: '^infrastructure/helm/.*'

  # Python
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  # Infrastructure & FinOps Security (Checkov)
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.1.52
    hooks:
      - id: checkov
        args: ["-d", "infrastructure/terraform/aws-finops-mock/", "--soft-fail"]

  # Native Local Hooks for Rust and Terraform (Windows & Monorepo Compatible)
  - repo: local
    hooks:
      # Rust
      - id: rust-fmt
        name: Rust Format
        entry: cargo fmt --manifest-path src/validator/Cargo.toml --
        language: system
        files: \.rs$
        pass_filenames: false

      - id: rust-clippy
        name: Rust Clippy
        entry: cargo clippy --manifest-path src/validator/Cargo.toml -- -D warnings
        language: system
        files: \.rs$
        pass_filenames: false

      # Terraform
      - id: terraform-fmt
        name: Terraform Format
        entry: terraform fmt -recursive infrastructure/terraform/
        language: system
        files: \.tf$
        pass_filenames: false

      - id: terraform-tflint
        name: Terraform TFLint
        entry: tflint -f compact --recursive
        language: system
        files: \.tf$
        pass_filenames: false

  # Temporarily disabled due to Windows AppLocker (WinError 4551).
  # Uncomment this if you move development to WSL or Linux.
  # - repo: https://github.com/gitleaks/gitleaks
  #   rev: v8.18.2
  #   hooks:
  #     - id: gitleaks
