version: '3.8'

services:
  # --- Service: Redpanda ---
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.2
    container_name: sentinel-redpanda
    command:
      - redpanda
      - start
      - --mode dev-container
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "9092:9092"
      - "19092:19092"
      - "9644:9644"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - sentinel_net

  console:
    image: docker.redpanda.com/redpandadata/console:v2.4.5
    container_name: sentinel-console
    ports:
      - "8080:8080"
    entrypoint: /app/console
    environment:
      - KAFKA_BROKERS=redpanda:9092
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - sentinel_net

  # --- Service: Redis ---
  redis:
    image: redis:7-alpine
    container_name: sentinel-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - sentinel_net

  # --- Service: API ---
  api:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: sentinel-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDPANDA_BROKER=redpanda:9092
    depends_on:
      redis:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    networks:
      - sentinel_net

  # --- Service:: Consumer ---
  consumer:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: sentinel-consumer
    command: ["python", "-m", "src.consumer.main"]
    environment:
      - REDPANDA_BROKER=redpanda:9092
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - sentinel_net

  # --- Service: UI ---
  ui:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: sentinel-ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      api:
        condition: service_started
    networks:
      - sentinel_net

networks:
  sentinel_net:
    driver: bridge
