apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: ui
  ports:
    - protocol: TCP
      port: {{ .Values.ui.service.port }}
      targetPort: 8501
