api:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-api"
    tag: "d343658"
validator:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-validator"
    tag: "d343658"
consumer:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-consumer"
    tag: "d343658"
