# Sentinel Global Helm Chart Values
global:
  environment: production
  imagePullPolicy: IfNotPresent

# Go Gateway
api:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/enesgulerdev/sentinel-api
    tag: b60abfb
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8000
  env:
    - name: REDPANDA_BROKER
      value: "redpanda:9092"
    - name: REDIS_HOST
      value: "redis"
    - name: REDIS_URL
      value: "redis:6379"
    - name: POSTGRES_HOST
      value: "postgres"
    - name: POSTGRES_PORT
      value: "5432"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger:4318/v1/traces"
  resources:
    requests:
      cpu: "500m"
      memory: "128Mi"
    limits:
      cpu: "2000m"
      memory: "256Mi"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
    targetMemoryAverageValue: "100Mi"

# Rust Validator
validator:
  enabled: true
  replicaCount: 2
  image:
    repository: ghcr.io/enesgulerdev/sentinel-validator
    tag: b60abfb
    pullPolicy: IfNotPresent
  env:
    - name: REDPANDA_BROKER
      value: "redpanda:9092"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://jaeger:4318/v1/traces"
  resources:
    requests:
      cpu: "50m"
      memory: "16Mi"
    limits:
      cpu: "50m"
      memory: "16Mi"

# Python Consumer
consumer:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/enesgulerdev/sentinel-consumer
    tag: b60abfb
    pullPolicy: IfNotPresent
  env:
    - name: REDPANDA_BROKER
      value: "redpanda:9092"
    - name: DATABASE_URL
      value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
  resources:
    requests:
      cpu: "1000m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "256Mi"

# Infrastructure
postgres:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

redis:
  enabled: true
  image:
    repository: docker.dragonflydb.io/dragonflydb/dragonfly
    tag: "latest"
  resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

redpanda:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

console:
  enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
