api:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-api"
    tag: "34c5368"
validator:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-validator"
    tag: "34c5368"
consumer:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-consumer"
    tag: "34c5368"
