api:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-api"
    tag: "ef20e95"
validator:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-validator"
    tag: "ef20e95"
consumer:
  image:
    repository: "ghcr.io/enesgulerdev/sentinel-consumer"
    tag: "ef20e95"
