{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: sentinel-api-service
  labels:
    app: sentinel-api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app: sentinel-api
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
{{- end }}
