apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-ui
  template:
    metadata:
      labels:
        app: sentinel-ui
    spec:
      containers:
        - name: ui
          image: sentinel-ui:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501
          env:
            - name: API_URL
              value: "http://api-service:8000"
