apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: sentinel
spec:
  type: LoadBalancer
  selector:
    app: sentinel-ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501