apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
spec:
  type: ClusterIP
  selector:
    app: redpanda
  ports:
    - protocol: TCP
      port: {{ .Values.redpanda.service.port }}
      targetPort: 9092
