apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-validator
  namespace: default
  labels:
    app: sentinel-validator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentinel-validator
  template:
    metadata:
      labels:
        app: sentinel-validator
    spec:
      initContainers:
      - name: wait-for-redpanda
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z redpanda 9092; do echo "Waiting for Redpanda to become ready..."; sleep 2; done;']
      containers:
        - name: validator
          image: ghcr.io/enesgulerdev/sentinel-validator:9e4cd78
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REDPANDA_BROKER
              value: "redpanda:9092"
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
