apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentinel-consumer
  template:
    metadata:
      labels:
        app: sentinel-consumer
    spec:
      initContainers:
      - name: wait-for-redpanda
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv redpanda 9092; do echo waiting for redpanda; sleep 2; done"]
      - name: wait-for-postgres
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv postgres 5432; do echo waiting for postgres; sleep 2; done"]

      containers:
      - name: consumer
        image: sentinel-consumer:1.0.0 # Versiyonu güncelledik!
        imagePullPolicy: IfNotPresent
        command: ["python", "-m", "src.inference.consumer"]

        envFrom:
        - secretRef:
            name: postgres-secret

        env:
        - name: REDPANDA_BROKER
          value: "redpanda:9092"
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
