apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      initContainers:
      - name: wait-for-api
        image: busybox:1.28
        command: ['sh', '-c', "until nc -zv api 8000; do echo waiting for api; sleep 2; done"]
      containers:
      - name: ui
        image: sentinel-ui:v0.5.0
        imagePullPolicy: IfNotPresent
        env:
        - name: API_URL
          value: "http://api:8000"
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "128Mi"
          limits:
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
